#=========================================================================
# run_test.yml
#=========================================================================
# Workflow to run PyMTL3 tests

name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_cmd:
          - ../rsa_xcel_naive ../rsa_xcel_mont

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Install Verilator
      run: |
        wget https://github.com/cornell-brg/verilator-travisci-cache/raw/master/verilator-travis-4.036.tar.gz
        tar -C ${HOME} -xzf verilator-travis-4.036.tar.gz
        echo "VERILATOR_ROOT=${HOME}/verilator" >> $GITHUB_ENV
        echo "PYMTL_VERILATOR_INCLUDE_DIR=${HOME}/verilator/share/verilator/include" >> $GITHUB_ENV
        echo "${HOME}/verilator/bin" >> $GITHUB_PATH

    - name: Check Verilator
      run: |
        echo ${VERILATOR_ROOT}
        echo ${PYMTL_VERILATOR_INCLUDE_DIR}
        verilator --version

    - name: Install dependencies
      run: |
        sudo apt-get install -y graphviz
        pip install --upgrade pip
        pip install -U git+https://github.com/cornell-brg/pymtl3@ece4750-2022
        pip install rsa

    - name: Run tests
      timeout-minutes: 5
      run: |
        mkdir -p hw/build && cd hw/build
        pytest ${{ matrix.test_cmd }} --verbose